#!/usr/bin/env bash
# Powers-of-Tau (bls12381) + Groth16 trusted setup for the Sharibo circuit.
#
# This is a hackathon-demo trusted setup: single contributor, random entropy
# from /dev/urandom. Real deployments would run a multi-party ceremony. See
# README "Honest limitations".
#
# After a successful run this script appends a fingerprint entry to
# circuits/SETUP_TRANSCRIPT.md so the canonical artifacts are always
# traceable.  ⚠️  Re-running setup produces a NEW verification key —
# any on-chain circle created with the previous vk will be permanently
# incompatible with proofs generated by the new key.
set -euo pipefail
cd "$(dirname "$0")/.."

BUILD=build
CURVE=bls12381
PTAU_POWER=12
PTAU_FINAL="$BUILD/pot${PTAU_POWER}_${CURVE}_final.ptau"
TRANSCRIPT="SETUP_TRANSCRIPT.md"

mkdir -p "$BUILD"

if [ ! -f "$BUILD/membership.r1cs" ]; then
  echo "membership.r1cs not found — run scripts/compile.sh first" >&2
  exit 1
fi

if [ ! -f "$PTAU_FINAL" ]; then
  npx --yes snarkjs powersoftau new "$CURVE" "$PTAU_POWER" "$BUILD/pot${PTAU_POWER}_${CURVE}_0000.ptau" -v
  npx --yes snarkjs powersoftau contribute "$BUILD/pot${PTAU_POWER}_${CURVE}_0000.ptau" "$BUILD/pot${PTAU_POWER}_${CURVE}_0001.ptau" \
    --name="Sharibo phase1 contribution" -v -e="$(head -c 64 /dev/urandom | base64)"
  npx --yes snarkjs powersoftau prepare phase2 "$BUILD/pot${PTAU_POWER}_${CURVE}_0001.ptau" "$PTAU_FINAL" -v
fi

npx --yes snarkjs groth16 setup "$BUILD/membership.r1cs" "$PTAU_FINAL" "$BUILD/membership_0000.zkey"
npx --yes snarkjs zkey contribute "$BUILD/membership_0000.zkey" "$BUILD/membership_final.zkey" \
  --name="Sharibo circuit key contribution" -v -e="$(head -c 64 /dev/urandom | base64)"
npx --yes snarkjs zkey export verificationkey "$BUILD/membership_final.zkey" verification_key.json

hash_file() {
  # Portable SHA-256: prefer sha256sum (Linux/WSL), fall back to shasum (macOS).
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$1" | awk '{print $1}'
  else
    echo "sha256-unavailable"
  fi
}

hash_file verification_key.json > verification_key.json.sha256
hash_file "$BUILD/membership_js/membership.wasm" > membership.wasm.sha256
hash_file "$BUILD/membership_final.zkey" > membership_final.zkey.sha256

echo "Setup complete -> build/membership_final.zkey, verification_key.json"

# ── Transcript fingerprinting ────────────────────────────────────────────────
SNARKJS_VERSION="$(npx --yes snarkjs --version 2>&1 | head -n1 | sed 's/snarkjs@//')"
DATE_NOW="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"

HASH_VK="$(hash_file verification_key.json)"
HASH_ZKEY="$(hash_file "$BUILD/membership_final.zkey")"
HASH_PTAU="$(hash_file "$PTAU_FINAL")"

# Create the transcript file with a header if it doesn't exist yet.
if [ ! -f "$TRANSCRIPT" ]; then
cat > "$TRANSCRIPT" << 'HEADER'
# Sharibo Trusted-Setup Transcript

Each entry below records one ceremony run.  The **verification key hash** is
the authoritative fingerprint: it must match `shasum -a 256 verification_key.json`
(or `sha256sum verification_key.json` on Linux) for any set of local artifacts
to be considered canonical.

> ⚠️ **A new `setup.sh` run produces a brand-new verification key.**
> Any on-chain circle created with a previous vk stores that old key
> inside its contract state (written at `create_circle` time).  Proofs
> generated from the new key will **fail** to verify against those circles.
> All existing circles must be cancelled and recreated after a key rotation.

---

HEADER
fi

# Append the new entry.
cat >> "$TRANSCRIPT" << ENTRY
## Entry — $DATE_NOW

| Field              | Value |
|--------------------|-------|
| Date (UTC)         | \`$DATE_NOW\` |
| snarkjs version    | \`$SNARKJS_VERSION\` |
| Curve              | \`$CURVE\` |
| Powers-of-Tau power | $PTAU_POWER |
| \`verification_key.json\` SHA-256 | \`$HASH_VK\` |
| \`membership_final.zkey\` SHA-256  | \`$HASH_ZKEY\` |
| \`${PTAU_FINAL##*/}\` SHA-256  | \`$HASH_PTAU\` |

> Note: \`membership_final.zkey\` and the ptau file are **not committed** to the
> repository (they are large binary files listed in .gitignore).  Only
> \`verification_key.json\` and this transcript are committed.  To verify
> locally, rerun \`scripts/compile.sh && scripts/setup.sh\` and compare the
> \`verification_key.json\` hash against the entry above.

---

ENTRY

echo "Transcript appended -> $TRANSCRIPT"
echo "  verification_key.json SHA-256: $HASH_VK"
